FROM node:20-alpine

RUN addgroup -S sandbox && adduser -S sandbox -G sandbox
RUN rm -rf /usr/local/lib/node_modules/npm

WORKDIR /sandbox
USER sandbox

CMD ["node", "--experimental-vm-modules", "/sandbox/code.js"]
